name: build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device:
        description: 'select device to build'
        default: 'r2s'
        required: false
      branch:
        description: 'seleclt openwrt branch'
        default: 'master'
        required: false

jobs: 
	build_packages:
		runs-on: ubuntu-latest
	steps:
		- name: build_packages
			run: |
				sudo apt update -y
				sudo apt full-upgrade -y
				sudo apt install -y --no-install-recommends ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
				bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
				genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
				libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
				libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf \
				python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
				swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
		- name: Update feeds and packages
			run: |
				git clone --depth=1 https://github.com/coolsnowwolf/lede lede
				cd lede 
				./scripts/feeds update -a
				./scripts/feeds install -a
				cat $GITHUB_WORKSPACE/r2s/def.config >.config
				make defconfig && make -j`nproc` download
				make -j`nproc` tools/compile toolchain/compile buildinfo target/compile package/compile package/install target/install
