## Remote package repositories

https://mirror.nju.edu.cn/immortalwrt/snapshots/targets/rockchip/armv8/kmods/6.12.60-1-fce6b393807cd9366f9cc99f8d023ac6/packages.adb
https://mirror.nju.edu.cn/immortalwrt/snapshots/targets/rockchip/armv8/packages/packages.adb
https://mirror.nju.edu.cn/immortalwrt/snapshots/packages/aarch64_generic/packages/packages.adb
https://mirror.nju.edu.cn/immortalwrt/snapshots/packages/aarch64_generic/luci/packages.adb
https://mirror.nju.edu.cn/immortalwrt/snapshots/packages/aarch64_generic/base/packages.adb
#the local package repository, do not remove!
#src imagebuilder file:packages
#arch aarch64_generic 100
