## Remote package repositories

src/gz 1 https://mirrors.nju.edu.cn/immortalwrt/releases/23.05.0/targets/rockchip/armv8/kmods/5.15.137-1-5c957c194634042fa20248343e768213
src/gz 2 https://mirrors.nju.edu.cn/immortalwrt/releases/23.05.0/packages/aarch64_generic/base
src/gz 3 https://mirrors.nju.edu.cn/immortalwrt/releases/23.05.0/packages/aarch64_generic/packages
src/gz 4 https://mirrors.nju.edu.cn/immortalwrt/releases/23.05.0/packages/aarch64_generic/luci
src/gz 5 https://mirrors.nju.edu.cn/immortalwrt/releases/23.05.0/targets/rockchip/armv8/packages
## This is the local package repository, do not remove!
src imagebuilder file:packages
arch aarch64_generic 100
