name: make_firmware

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device:
        description: 'select device to build'
        default: 'r2s'
        required: false
      branch:
        description: 'seleclt openwrt branch'
        default: 'master'
        required: false

jobs: 

  build_packages:
    name: build r2s firmware
    runs-on: ubuntu-latest
    steps:
      - name: setup1
        run: |       
                sudo apt install -y --no-install-recommends ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
                bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
                genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
                libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
                libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf \
                python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
                swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup2
        run: |
                  ulimit -SHn 65000
                  git clone -b openwrt-24.10 https://github.com/immortalwrt/immortalwrt ~/lede
                  cd ~/lede 
      - name: setup3
        run: |
                  cd ~/lede
                  ./scripts/feeds update -a
      - name: setup4
        run: |
                  cd ~/lede
                  ./scripts/feeds install -a
      - name: setup09
        run: |
                  cd ~/lede
                  cat $GITHUB_WORKSPACE/config/${{ github.event.inputs.device }}.config >.config
                  make defconfig && make -j`nproc` download
                  
      - name: setup10
        run: |
                  cd ~/lede
                  make -j`nproc` tools/compile toolchain/compile buildinfo target/compile package/compile package/install target/install
                  echo "strDate=$(TZ=UTC-8 date +%m-%d-%H-%M)" >> $GITHUB_ENV
                  mkdir -p $GITHUB_WORKSPACE/release/
                  mv -v ./bin/targets/*/*/*.img.gz  $GITHUB_WORKSPACE/release/
                  mv -v ./bin/targets/*/*/*imagebuilder*xz  $GITHUB_WORKSPACE/release/
      - name: Upload release asset
        uses: softprops/action-gh-release@v2.2.1
        with: 
          tag_name: ${{env.strDate}}         
          name:  自动发布
          files: |
              ./release/* 
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
